---
###############################################################################
#                                                                             #
#                            WEBSITE CONFIGURATION                            #
#                                                                             #
###############################################################################


# --- base website settings ---

baseURL: https://11pmbuddy.me/
title: 11 PM Buddy
theme: inventory
languageCode: en-us
enableEmoji: true
enableGitInfo: true

# Optional: Add Google Analytics tracking support.
googleAnalytics: ""


# --- security settings ---

security:
  exec:
    allow: ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']


# --- markup settings ---

markup:
  asciidocExt:
    preserveTOC: true
    sectionNumbers: true
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    style: murphy
    tabWidth: 4


# --- privacy settings ---

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
  twitter:
    enableDNT: true
  vimeo:
    enableDNT: true
  youtube:
    privacyEnhanced: true


# --- custom settings ---

params:
  # "Edit this page" feature: git forge content base link
  # [Example] editPrefix: https://github.com/username/repo-name/blob/main/content
  # editPrefix: https://github.com/unicef/inventory-hugo-theme/blob/main/exampleSite/content

  # Shown on all pages. When logo is empty, it will show your site title, set above.
  logo: ""

  # OpenGraph data
  description: 11 PM Buddy, a note sharing website for students, by the students.
  author: br0wnboi
  # Tip: Find a royalty-free image from unsplash.com for an OpenGraph image.
  image: "images/banner.jpg"

  # customize color
  primary_color: "#212124"
  primary_color_light: "#1b66b1"
  body_color: "#f2f4f6"
  text_color: "#636363"
  text_color_dark: "#374ea2"
  text_title_color: "#ffffff"
  white_color: "#ffffff"
  light_color: "#f8f9fa"

  # font family (choose from https://fonts.google.com/)
  font_family: "Lato"

  # contact form action (works with https://formspree.io)
  contact_form_action: "#"

  # related article number limit
  article_count: 3

  # brand and identity information
  brand:
    parent_org_name: 11 PM Buddy
    parent_org_url: https://11pmbuddy.me/
    parent_org_url_legal: https://11pmbuddy.me/
  footer:
    mainSite: https://11pmbuddy.me/
    mainSiteName: 11PM Buddy


# --- social platform settings ---
# themify icon pack : https://themify.me/themify-icons

  social:
    - icon: ti-github
      name: 11PM Buddy Source
      link: https://github.com/11pmbuddy/11pmbuddy-test
    - icon: ti-twitter-alt
      name: "@UNICEFinnovate on Twitter"
      link: https://twitter.com/UNICEFinnovate


# --- taxonomy settings ---

taxonomies:
  alert: alerts
  category: categories
  downloadable: downloadBtn


# --- multilingual settings ---

Languages:
############################# English #############################
  en:
    languageName: en
    languageCode: en-us
    weight: 1
    home: Home
    copyright: "Copyright &copy; 2023 a Hugo theme by [UNICEF Office of Innovation](https://www.unicef.org/innovation/)"
    params:
      banner:
        title: 11 PM Buddy
        subtitle: 11 PM Buddy is a note sharing for NFSU students, by NFSU students.
        bg_image: images/banner.jpg
        placeholder: Search your notes here.
      cta:
        enable: true
        title: Submit your notes
        content: Use the google form below to submit your notes and help out other fellow students.
        button:
          enable: true
          label: Contribute
          link: contact
      footer:
        description: Powered by Hugo, a static site generator.

    # --- navigation menu ---
    menu:
      main:
        - name: FAQ
          weight: 10
          url: faq
        - name: Contact
          weight: 20
          url: contact

        - name: courses
          weight: 50
          url: courses
          hasChildren: true
        # Sub-pages in this drop-down should correspond to categories created in /content/
        - name: Msc. CS
          parent: courses
          weight: 10
          url: courses/msc-cs/
        - name: Msc. DFIS
          parent: courses
          weight: 20
          url: courses/msc-dfis/
        - name: B.Tech
          parent: courses
          weight: 20
          url: courses        


############################# español / Spanish #############################
  # es:
    # languageName: es
    # languageCode: es-mx
    # weight: 2
    # home: Página principal
    # copyright: "Copyright &copy; 2020-2022 una plantilla de [UNICEF Office of Innovation](https://www.unicef.org/innovation/)"
    # params:
    #   banner:
    #     title: Plantilla de UNICEF Inventory
    #     subtitle: Documentación y un sitio de ejemplo de la plantilla de UNICEF Inventory. Construido para Hugo, un generador de sitios estáticos.
    #     bg_image: images/banner.jpg
    #     placeholder: ¿Ud. tiene una pregunta? Usted busca el sitio aquí.
    #   cta:
    #     enable: true
    #     title: Integración de Formspree
    #     content: Cree un formulario de contacto rápido y fácil para que los visitantes del sitio se comuniquen con la integración integrada de Formspree.
    #     button:
    #       enable: true
    #       label: Ver el formulario
    #       link: contact
    #   footer:
    #     description: Documentación de la plantilla de UNICEF Inventory y sitio de ejemplo. Desarrollado por Hugo, un generador de sitio estático. Una herramienta de open source de la Oficina de Innovación de UNICEF, Ventures Team.

    # # --- navigation menu ---
    # menu:
    #   main:
    #     - name: FAQ
    #       weight: 10
    #       url: faq
    #     - name: Contactar
    #       weight: 20
    #       url: contact

    #     - name: pages
    #       weight: 50
    #       url: pages
    #       hasChildren: true
    #     # Sub-pages in this drop-down should correspond to categories created in /content/
    #     - name: 1. Sobre
    #       parent: pages
    #       weight: 10
    #       url: about
    #     - name: 2. Características
    #       parent: pages
    #       weight: 20
    #       url: features
    #     - name: 3. Instalación
    #       parent: pages
    #       weight: 30
    #       url: install
    #     - name: 4. Contribuyendo
    #       parent: pages
    #       weight: 50
    #       url: contributing
